const projecyData = [
  {
    id: 1,
    type: "react",
    img: "./assets/food-ecommerce-reactjs.png",
    title: "Food-E-commerce",
    description: "Html - Css - Reactjs - reduxToolkit",
    link: "https://food-ecommerce-142b3.web.app/",
    git: "",
  },
  {
    id: 2,
    type: "js",
    img: "./assets/e-commerce-project-js.png",
    title: "Ecommerce-Project-js",
    description: "Html - Css (Sass) - Js",
    link: "https://js-e-commerce-project.vercel.app/",
    git: "",
  },
  {
    id: 3,
    type: "js",
    img: "./assets/dashboard-html-css.png",
    title: "Dashboard",
    description: "Html - Css",
    link: "https://dashboard-html-css-pied.vercel.app/",
    git: "",
  },
  {
    id: 4,
    type: "react",
    img: "./assets/millionaire-quiz-app-reactjs.png",
    title: "millionaire-quiz-app-reactjs",
    description: "Html - Css - reactjs ",
    link: "https://millionaire-quiz-app-six.vercel.app/",
    git: "",
  },
  {
    id: 5,
    type: "js",
    img: "./assets/template-one-leon-vercel-app-html-css.png",
    title: "leon-template-one",
    description: "Html - Css - javascript",
    link: "https://template-one-leon.vercel.app/",
    git: "",
  },
  {
    id: 6,
    type: "react",
    img: "./assets/movies-app-react-js.png",
    title: "movies-app-react-js",
    description: "Html - Css - react-js",
    link: "https://movies-app-react-js-omega.vercel.app/",
    git: "",
  },
  {
    id: 7,
    type: "js",
    img: "./assets/full-website-barber.png",
    title: "full-website-barber",
    description: "Html - Css - Javascript",
    link: "https://website-barber.vercel.app/",
    git: "",
  },
  {
    id: 8,
    type: "js",
    img: "./assets/responsive-animate-food.png",
    title: "responsive-animate-food",
    description: "Html - Css - Javascript",
    link: "https://responsive-animate-food.vercel.app/",
    git: "",
  },
];

export default projecyData;
